config/routes.rb
Rails.application.routes.draw do

  resources :resultpage

  resources :resultvariants

  resources :symptom_categories

  resources :when_categories

  resources :where_categories

  resources :what_categories

  devise_for :users
  resources :dashboard
  resources :diagnostics

  root to: 'home#index'

  resources :what_categories do
    resources :where_categories do
      resources :when_categories do
        resources :symptom_categories do
          resources :resultvariants
          resources :resultpage
        end
      end
    end
  end

end

app/models/resultvariant.rb
class Resultvariant < ActiveRecord::Base
  belongs_to :symptom_category
end

app/models/symptom_category.rb
class SymptomCategory < ActiveRecord::Base
  belongs_to :when_category
  has_many :resultvariants
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/what_category.rb
class WhatCategory < ActiveRecord::Base
  has_many :where_categories
end

app/models/when_category.rb
class WhenCategory < ActiveRecord::Base
  belongs_to :where_category
  has_many :symptom_categories
end

app/models/where_category.rb
class WhereCategory < ActiveRecord::Base
  belongs_to :what_category
  has_many :when_categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_filter :authenticate_user!
  def index

  end

  def to_diagnostics
    # @diagnostics = .find()
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to :controller => 'dashboard', :action => 'index'
    end
  end


end

app/controllers/resultpage_controller.rb
class ResultpageController < ApplicationController

  def index

  end

end

app/controllers/when_categories_controller.rb
class WhenCategoriesController < ApplicationController
  before_action :set_when_category, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @when_categories = WhenCategory.all
    respond_with(@when_categories)
  end

  def show
    respond_with(@when_category)
  end

  def new
    @when_category = WhenCategory.new
    @when_category.where_category_id = params[:where_category_id]
    # respond_with(@when_category)
  end

  def edit
  end

  def create
    @when_category = WhenCategory.new(when_category_params)
    @when_category.save
    respond_with(@when_category)
  end

  def update
    @when_category.update(when_category_params)
    respond_with(@when_category)
  end

  def destroy
    @when_category.destroy
    respond_with(@when_category)
  end

  private
    def set_when_category
      @when_category = WhenCategory.find(params[:id])
    end

    def when_category_params
      params.require(:when_category).permit(:title, :description, :where_category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/haunt_variants_helper.rb
module HauntVariantsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/resultpage_helper.rb
module ResultpageHelper
end

app/helpers/resultvariants_helper.rb
module ResultvariantsHelper
end

app/helpers/symptom_categories_helper.rb
module SymptomCategoriesHelper
end

app/helpers/what_categories_helper.rb
module WhatCategoriesHelper
end

app/helpers/when_categories_helper.rb
module WhenCategoriesHelper
end

app/helpers/where_categories_helper.rb
module WhereCategoriesHelper
end

app/views/when_categories/_form.html.erb
<%= form_for(@when_category) do |f| %>
  <% if @when_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@when_category.errors.count, "error") %> prohibited this when_category from being saved:</h2>

      <ul>
      <% @when_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :where_category_id %><br>
    <%= f.number_field :where_category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/when_categories/edit.html.erb
<h1>Editing when_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @when_category %> |
<%= link_to 'Back', when_categories_path %>

app/views/when_categories/index.html.erb
<h1>Listing when_categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Where category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @when_categories.each do |when_category| %>
      <tr>
        <td><%= when_category.title %></td>
        <td><%= when_category.description %></td>
        <td><%= when_category.where_category_id %></td>
        <td><%= link_to 'Show', when_category %></td>
        <td><%= link_to 'Edit', edit_when_category_path(when_category) %></td>
        <td><%= link_to 'Destroy', when_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New When category', new_when_category_path %>

app/views/when_categories/new.html.erb
<h1>New when_category</h1>

<%= render 'form' %>

<%= link_to 'Back', when_categories_path %>

app/views/when_categories/show.html.erb
<p id="notice"><%= notice %></p>

<div class = "title_description_combo">
    <p>
      <strong>Title:</strong>
      <%= @when_category.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @when_category.description %>
    </p>

    <p>
      <strong>Where category:</strong>
      <%= @when_category.where_category_id %>
    </p>
</div>


<div class = "display_selections">
<!--DISPLAY CHILDREN-->

<% @when_category.symptom_categories.each do |symptom_category| %> 

    <div class = 'selections'> 
      <h3><%= symptom_category.title %></h3>  
      <p> 
        <%= link_to 'CHOOSE', symptom_category_path(symptom_category), :class => 'btn btn-default' %> 
      </p>  
    </div> 

<%end%> 

<!-- END DISPLAY CHILDREN-->
  </div>



<%= link_to 'Edit', edit_when_category_path(@when_category) %> |
<%= link_to 'Back', when_categories_path %>