config/routes.rb
Rails.application.routes.draw do

  resources :resultpage

  resources :resultvariants

  resources :symptom_categories

  resources :when_categories

  resources :where_categories

  resources :what_categories

  devise_for :users
  resources :dashboard
  resources :diagnostics

  root to: 'home#index'

  resources :what_categories do
    resources :where_categories do
      resources :when_categories do
        resources :symptom_categories do
          resources :resultvariants
          resources :resultpage
        end
      end
    end
  end

end

app/models/resultvariant.rb
class Resultvariant < ActiveRecord::Base
  belongs_to :symptom_category
end

app/models/symptom_category.rb
class SymptomCategory < ActiveRecord::Base
  belongs_to :when_category
  has_many :resultvariants
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/what_category.rb
class WhatCategory < ActiveRecord::Base
  has_many :where_categories
end

app/models/when_category.rb
class WhenCategory < ActiveRecord::Base
  belongs_to :where_category
  has_many :symptom_categories
end

app/models/where_category.rb
class WhereCategory < ActiveRecord::Base
  belongs_to :what_category
  has_many :when_categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_filter :authenticate_user!
  def index

  end

  def to_diagnostics
    # @diagnostics = .find()
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to :controller => 'dashboard', :action => 'index'
    end
  end


end

app/controllers/resultpage_controller.rb
class ResultpageController < ApplicationController

  def index

  end

end

app/controllers/where_categories_controller.rb
class WhereCategoriesController < ApplicationController
  before_action :set_where_category, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @where_categories = WhereCategory.all
    respond_with(@where_categories)
  end

  def show
    respond_with(@where_category)
  end

  def new
    @where_category = WhereCategory.new
    @where_category.what_category_id = params[:what_category_id]
  end

  def edit
  end

  def create
    @where_category = WhereCategory.new(where_category_params)
    @where_category.save
    respond_with(@where_category)
  end

  def update
    @where_category.update(where_category_params)
    respond_with(@where_category)
  end

  def destroy
    @where_category.destroy
    respond_with(@where_category)
  end

  private
    def set_where_category
      @where_category = WhereCategory.find(params[:id])
    end

    def where_category_params
      params.require(:where_category).permit(:title, :description, :what_category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/haunt_variants_helper.rb
module HauntVariantsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/resultpage_helper.rb
module ResultpageHelper
end

app/helpers/resultvariants_helper.rb
module ResultvariantsHelper
end

app/helpers/symptom_categories_helper.rb
module SymptomCategoriesHelper
end

app/helpers/what_categories_helper.rb
module WhatCategoriesHelper
end

app/helpers/when_categories_helper.rb
module WhenCategoriesHelper
end

app/helpers/where_categories_helper.rb
module WhereCategoriesHelper
end

app/views/where_categories/_form.html.erb
<%= form_for(@where_category) do |f| %>
  <% if @where_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@where_category.errors.count, "error") %> prohibited this where_category from being saved:</h2>

      <ul>
      <% @where_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :what_category_id %><br>
    <%= f.number_field :what_category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/where_categories/edit.html.erb
<h1>Editing where_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @where_category %> |
<%= link_to 'Back', where_categories_path %>

app/views/where_categories/index.html.erb
<h1>Listing where_categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>What category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @where_categories.each do |where_category| %>
      <tr>
        <td><%= where_category.title %></td>
        <td><%= where_category.description %></td>
        <td><%= where_category.what_category_id %></td>
        <td><%= link_to 'Show', where_category %></td>
        <td><%= link_to 'Edit', edit_where_category_path(where_category) %></td>
        <td><%= link_to 'Destroy', where_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Where category', new_where_category_path %>

app/views/where_categories/new.html.erb
<h1>New where_category</h1>

<%= render 'form' %>

<%= link_to 'Back', where_categories_path %>

app/views/where_categories/show.html.erb
<p id="notice"><%= notice %></p>

<div class = "title_description_combo">
    <p>
      <strong>Title:</strong>
      <%= @where_category.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @where_category.description %>
    </p>

    <p>
      <strong>What category:</strong>
      <%= @where_category.what_category_id %>
    </p>
</div>


<div class = "display_selections">
<!--DISPLAY CHILDREN-->

<% @where_category.when_categories.each do |when_category| %> 

    <div class = 'selections'> 
      <h3><%= when_category.title %></h3>  

      <p> 
        <%= link_to 'CHOOSE', when_category_path(when_category), :class => 'btn btn-default' %> 
      </p>  
    </div> 

<%end%> 

<!-- END DISPLAY CHILDREN-->
</div>




<%= link_to 'Edit', edit_where_category_path(@where_category) %> |
<%= link_to 'Back', where_categories_path %>