config/routes.rb
Rails.application.routes.draw do

  resources :resultpage

  resources :resultvariants

  resources :symptom_categories

  resources :when_categories

  resources :where_categories

  resources :what_categories

  devise_for :users
  resources :dashboard
  resources :diagnostics

  root to: 'home#index'

  resources :what_categories do
    resources :where_categories do
      resources :when_categories do
        resources :symptom_categories do
          resources :resultvariants
          resources :resultpage
        end
      end
    end
  end

end

app/models/resultvariant.rb
class Resultvariant < ActiveRecord::Base
  belongs_to :symptom_category
end

app/models/symptom_category.rb
class SymptomCategory < ActiveRecord::Base
  belongs_to :when_category
  has_many :resultvariants
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/what_category.rb
class WhatCategory < ActiveRecord::Base
  has_many :where_categories
end

app/models/when_category.rb
class WhenCategory < ActiveRecord::Base
  belongs_to :where_category
  has_many :symptom_categories
end

app/models/where_category.rb
class WhereCategory < ActiveRecord::Base
  belongs_to :what_category
  has_many :when_categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_filter :authenticate_user!
  def index

  end

  def to_diagnostics
    # @diagnostics = .find()
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to :controller => 'dashboard', :action => 'index'
    end
  end


end

app/controllers/resultpage_controller.rb
class ResultpageController < ApplicationController

  def index

  end

end

app/controllers/symptom_categories_controller.rb
class SymptomCategoriesController < ApplicationController
  before_action :set_symptom_category, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @symptom_categories = SymptomCategory.all
    respond_with(@symptom_categories)
  end

  def show
    respond_with(@symptom_category)
  end

  def new
    @symptom_category = SymptomCategory.new
    @symptom_category.when_category_id = params[:when_category_id]
    # respond_with(@symptom_category)
  end

  def edit
  end

  def create
    @symptom_category = SymptomCategory.new(symptom_category_params)
    @symptom_category.save
    respond_with(@symptom_category)
  end

  def update
    @symptom_category.update(symptom_category_params)
    respond_with(@symptom_category)
  end

  def destroy
    @symptom_category.destroy
    respond_with(@symptom_category)
  end

  private
    def set_symptom_category
      @symptom_category = SymptomCategory.find(params[:id])
    end

    def symptom_category_params
      params.require(:symptom_category).permit(:title, :description, :when_category_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/haunt_variants_helper.rb
module HauntVariantsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/resultpage_helper.rb
module ResultpageHelper
end

app/helpers/resultvariants_helper.rb
module ResultvariantsHelper
end

app/helpers/symptom_categories_helper.rb
module SymptomCategoriesHelper
end

app/helpers/what_categories_helper.rb
module WhatCategoriesHelper
end

app/helpers/when_categories_helper.rb
module WhenCategoriesHelper
end

app/helpers/where_categories_helper.rb
module WhereCategoriesHelper
end

app/views/symptom_categories/_form.html.erb
<%= form_for(@symptom_category) do |f| %>
  <% if @symptom_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@symptom_category.errors.count, "error") %> prohibited this symptom_category from being saved:</h2>

      <ul>
      <% @symptom_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :when_category_id %><br>
    <%= f.number_field :when_category_id %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/symptom_categories/edit.html.erb
<h1>Editing symptom_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @symptom_category %> |
<%= link_to 'Back', symptom_categories_path %>

app/views/symptom_categories/index.html.erb
<h1>Listing symptom_categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>When category</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @symptom_categories.each do |symptom_category| %>
      <tr>
        <td><%= symptom_category.title %></td>
        <td><%= symptom_category.description %></td>
        <td><%= symptom_category.when_category_id %></td>
        <td><%= symptom_category.image %></td>
        <td><%= link_to 'Show', symptom_category %></td>
        <td><%= link_to 'Edit', edit_symptom_category_path(symptom_category) %></td>
        <td><%= link_to 'Destroy', symptom_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Symptom category', new_symptom_category_path %>

app/views/symptom_categories/new.html.erb
<h1>New symptom_category</h1>

<%= render 'form' %>

<%= link_to 'Back', symptom_categories_path %>

app/views/symptom_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @symptom_category.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @symptom_category.description %>
</p>

<p>
  <strong>When category:</strong>
  <%= @symptom_category.when_category_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @symptom_category.image %>
</p>

<p>
  <%= link_to 'Go to Result Page', resultpage_url, :class => 'btn btn-default' %> 
</p>


<div class = "display_selections">
<!--DISPLAY CHILDREN-->

<% @symptom_category.resultvariants.each do |resultvariant| %> 

    <div class = 'selections'> 
      <h3><%= resultvariant.title %></h3>  

      <p> 
        <%= link_to 'CHOOSE',resultpage_path, :class => 'btn btn-default' %> 
      </p>  
    </div>


       

<%end%> 

<!-- END DISPLAY CHILDREN-->
  </div>




<%= link_to 'Edit', edit_symptom_category_path(@symptom_category) %> |
<%= link_to 'Back', symptom_categories_path %>