config/routes.rb
Rails.application.routes.draw do

  resources :resultpage

  resources :resultvariants

  resources :symptom_categories

  resources :when_categories

  resources :where_categories

  resources :what_categories

  devise_for :users
  resources :dashboard
  resources :diagnostics

  root to: 'home#index'

  resources :what_categories do
    resources :where_categories do
      resources :when_categories do
        resources :symptom_categories do
          resources :resultvariants
          resources :resultpage
        end
      end
    end
  end

end

app/models/resultvariant.rb
class Resultvariant < ActiveRecord::Base
  belongs_to :symptom_category
end

app/models/symptom_category.rb
class SymptomCategory < ActiveRecord::Base
  belongs_to :when_category
  has_many :resultvariants
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/what_category.rb
class WhatCategory < ActiveRecord::Base
  has_many :where_categories
end

app/models/when_category.rb
class WhenCategory < ActiveRecord::Base
  belongs_to :where_category
  has_many :symptom_categories
end

app/models/where_category.rb
class WhereCategory < ActiveRecord::Base
  belongs_to :what_category
  has_many :when_categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_filter :authenticate_user!
  def index

  end

  def to_diagnostics
    # @diagnostics = .find()
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to :controller => 'dashboard', :action => 'index'
    end
  end


end

app/controllers/resultpage_controller.rb
class ResultpageController < ApplicationController

  def index

  end

end

app/controllers/what_categories_controller.rb
class WhatCategoriesController < ApplicationController
  before_action :set_what_category, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @what_categories = WhatCategory.all
    respond_with(@what_categories)
  end

  def show
    respond_with(@what_category)
  end

  def new
    @what_category = WhatCategory.new
    respond_with(@what_category)
  end

  def edit
  end

  def create
    @what_category = WhatCategory.new(what_category_params)
    @what_category.save
    respond_with(@what_category)
  end

  def update
    @what_category.update(what_category_params)
    respond_with(@what_category)
  end

  def destroy
    @what_category.destroy
    respond_with(@what_category)
  end

  private
    def set_what_category
      @what_category = WhatCategory.find(params[:id])
    end

    def what_category_params
      params.require(:what_category).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/haunt_variants_helper.rb
module HauntVariantsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/resultpage_helper.rb
module ResultpageHelper
end

app/helpers/resultvariants_helper.rb
module ResultvariantsHelper
end

app/helpers/symptom_categories_helper.rb
module SymptomCategoriesHelper
end

app/helpers/what_categories_helper.rb
module WhatCategoriesHelper
end

app/helpers/when_categories_helper.rb
module WhenCategoriesHelper
end

app/helpers/where_categories_helper.rb
module WhereCategoriesHelper
end

app/views/what_categories/_form.html.erb
<%= form_for(@what_category) do |f| %>
  <% if @what_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@what_category.errors.count, "error") %> prohibited this what_category from being saved:</h2>

      <ul>
      <% @what_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/what_categories/edit.html.erb
<h1>Editing what_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @what_category %> |
<%= link_to 'Back', what_categories_path %>

app/views/what_categories/index.html.erb
<h1>Listing what_categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @what_categories.each do |what_category| %>
      <tr>
        <td><%= what_category.title %></td>
        <td><%= what_category.description %></td>
        <td><%= link_to 'Choose', what_category %></td>
        <td><%= link_to 'Edit', edit_what_category_path(what_category) %></td>
        <td><%= link_to 'Destroy', what_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New What category', new_what_category_path %>

app/views/what_categories/new.html.erb
<h1>New what_category</h1>

<%= render 'form' %>

<%= link_to 'Back', what_categories_path %>

app/views/what_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @what_category.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @what_category.description %>
</p>



<div class = "display_selections">
<!--DISPLAY CHILDREN-->

<% @what_category.where_categories.each do |where_category| %> 

    <div class = 'selections'> 
      <h3><%= where_category.title %></h3>  

      <p> 
        <%= link_to 'CHOOSE', where_category_path(where_category), :class => 'btn btn-default' %> 
      </p>  
    </div> 

<%end%> 

<!-- END DISPLAY CHILDREN-->
</div>


<%= link_to 'Edit', edit_what_category_path(@what_category) %> |
<%= link_to 'Back', what_categories_path %>